/* DB Statements
create table user(
id int GENERATED BY DEFAULT AS IDENTITY,
username nvarchar(100) not null,
password nvarchar(100) not null,
PRIMARY KEY (id))
 */
package model;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;

public class UserCreateDB {
	private String createUserString = "INSERT INTO user (username, password) VALUES (?,?)";
	private PreparedStatement createUser; 
	Connection connection = null;
			
	public boolean InsertUser(String username, String password){

		try {
			connection = DriverManager.getConnection( "jdbc:hsqldb:hsql://localhost/mydatabase", "SA", "" );
			createUser = connection.prepareStatement( createUserString );
			createUser.setString(1, hashPassword(password));
			createUser.setString(2, password);
			createUser.execute();

		} catch ( SQLException e ) {
			System.out.println( "Error opening connection to DB with statement: " + createUserString );
			return false;
		}
				
		return true;
	}

	private String hashPassword(String password) {
		String hashedPassword = null;
		try {
			MessageDigest digest = MessageDigest.getInstance("SHA-512");
			digest.update( password.getBytes() );
			byte[] hashedPasswordBytes = digest.digest();
			hashedPassword = new String( hashedPasswordBytes );
			
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		return hashedPassword;
	}
}
