/*
create table user(
id int GENERATED BY DEFAULT AS IDENTITY,
username nvarchar(100) not null,
password nvarchar(100) not null,
PRIMARY KEY (id))
 */
package model;

public class UserCreateDB {
	
	public static void InsertUser(User user){
		
	}
}
